config/routes.rb
Akihabara::Application.routes.draw do

  root 'stores#index'
  resources :stores

end

app/models/store.rb
class Store < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  def index
    @stores = Store.all
  end

  def new
    @store = Store.new
  end

  def create
    Store.create(store_params)
    redirect_to root_path
  end

  private

  def store_params
    params.require(:store).permit(:name, :description)
  end
end

app/helpers/akihabara_helper.rb
module AkihabaraHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/akihabara/index.html.erb
<div class="jumbotron">
  <div class="container">
    <h1 class="center">Welcome to Akihabara!</h1>
    <p>Akihabara (秋葉原), also called Akiba name after a former local shrine, is a district in central Tokyo that is famous for its many electronics shops. In more recent years, Akihabara has gained recognition as the center of Japan's otaku (diehard fan) culture, and many shops and establishments devoted to anime and manga are now dispersed among the electronic stores in the district.</p>
  </div>
</div>
<h1 class="center">Major Attractions</h1>
<% @stores.each do |store| %>
  <div class="booyah-box col-xs-10  col-xs-offset-1">
    <h1><%= store.name %></h1><br />
    <p><%= store.description %></p><br />
  </div>

  <hr />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Akihabara</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= tag :meta, name: "viewport", content: "width=device-width, initial-scale=1.0" %>
  <nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to 'Akihabara', root_path, class: 'navbar-brand' %>
      </div>
      <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <li>
            <%= link_to "New Store", new_store_path %>
          </li>
        </ul>
  </div>
</div>
</nav>
</head>
<body>


  <%= yield %>


</body>
</html>

app/views/stores/index.html.erb
<div class="jumbotron">
  <div class="container">
    <h1 class="center">Welcome to Akihabara!</h1>
    <p>Akihabara (秋葉原), also called Akiba name after a former local shrine, is a district in central Tokyo that is famous for its many electronics shops. In more recent years, Akihabara has gained recognition as the center of Japan's otaku (diehard fan) culture, and many shops and establishments devoted to anime and manga are now dispersed among the electronic stores in the district.</p>
  </div>
</div>
<br />
<h1 class="center">Major Attractions</h1>
<% @stores.each do |store| %>
  <div class="booyah-box col-xs-10  col-xs-offset-1">
    <h1><%= store.name %></h1><br />
    <p><%= store.description %></p><br />
  </div>

  <hr />
<% end %>

app/views/stores/new.html.erb
<div class="booyah-box col-xs-10 col-xs-offset-1">
  <h1>Enter Your Place Details</h1>
  <%= simple_form_for @store do |f| %>
    <%= f.input :name %>
    <%= f.input :description %>
    <br />
    <%= f.submit 'Create', class: 'btn btn-success' %>
  <% end %>
</div>